openapi: 3.0.1
info:
  title: COMPASSLIZA
  description: API de locação de carros que atua no seguimento de aluguel de carro de luxo e semi luxo. Com carros exclusivos disponibilizados em apenas um modelo por cidade.
  version: 0.0.1
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
    description: Github
    url: https://github.com/Tuanassf/DesafioFinal-compass
servers: 
  - url: http://localhost:3000/api/v1/
    description: API compassLiza
paths:
  /car:
   get:
      summary: Listar Todos os veículos cadastrados
      parameters:
      - name: modelo
        in: query
        schema:
          type: string
        required: false
      - name: cor
        in: query
        schema:
          type: string
        required: false
      - name: ano
        in: query
        schema:
          type: string
        required: false
      - name: quantidadePassageiros
        in: query
        schema:
          type: string
        required: false
      responses:
        200:
          description: Sucesso
          content:
           application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    modelo:
                      type: string
                    cor: 
                      type: string
                    ano:
                      type: number
                    acessorios:
                      type: array
                      items:
                        type: object
                        properties:
                          descricao:
                            type: string
                    quantidadePassageiros:
                      type: number
  /car/{id}:
    get:
      summary: Listar um veículo através do id
      parameters: 
        - name: id
          in: path
          schema:
            type: string
          required: true  
      responses:
        200:
          description: sucesso
          content:
           application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    modelo:
                      type: string
                    cor: 
                      type: string
                    ano:
                      type: number
                    acessorios:
                      type: array
                      items:
                        type: object
                        properties:
                          descricao:
                            type: string
                    quantidadePassageiros:
                      type: number